name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        npx -p @skyux-sdk/cli skyux certs install
        npm ci
    - name: Coverage
      run: |
        npm run build
        npm run test
        bash <(curl -s https://codecov.io/bash)
